using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerLook : MonoBehaviour
{
	public float sensitivity = 1.0f;
	float verticalRotation = 0;
	public float upDownRange = 70.0f;
    // Start is called before the first frame update
    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
    	//Screen.lockCursor = true;
    }

    // Update is called once per frame
    void Update()
    {	
        if (Input.GetKey(KeyCode.Space))
            Cursor.lockState = Cursor.lockState == CursorLockMode.Locked ? CursorLockMode.None : CursorLockMode.Locked;

        if (Cursor.lockState == CursorLockMode.Locked)
        {
		    float rotLeftRight = Input.GetAxis("Mouse X") * sensitivity;
		    transform.Rotate(0, rotLeftRight, 0);

		    
		    verticalRotation -= Input.GetAxis("Mouse Y") * sensitivity;
		    verticalRotation = Mathf.Clamp(verticalRotation, -upDownRange, upDownRange);
		    Camera.main.transform.localRotation = Quaternion.Euler(verticalRotation, 0, 0);
        }
    }
}
